pipeline:
  identifier: Build_CypressTest_1699177131169
  name: Build CypressTest
  orgIdentifier: default
  projectIdentifier: CypressTest
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1699177121032
        repoName: CypressTest
  stages:
    - stage:
        identifier: build
        name: Test
        spec:
          cloneCodebase: true
          execution:
            steps:
              - parallel:
                  - step:
                      identifier: npminstall
                      name: npm_install
                      spec:
                        command: npm install
                      timeout: ""
                      type: Run
                  - step:
                      type: Run
                      name: Redefine
                      identifier: Redefine
                      spec:
                        shell: Sh
                        command: |-
                          echo $HARNESS_BUILD_ID
                          echo $HARNESS_EXECUTION_ID
                          ehco $HARNESS_PIPELINE_ID
                          echo $HARNESS_PROJECT_ID
                          echo $HARNESS_STAGE_ID
              - step:
                  identifier: npmtest
                  name: npm_test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          caching:
            enabled: false
            paths: []
        type: CI
        description: ""
